name: iapr-project
channels:
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.3.7
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - expat=2.6.2
  - libffi=3.4.4
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.13
  - pandas=2.2.1
  - pip=24.0
  - python=3.12.3
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024a
  - vc=14.2
  - vs2015_runtime=14.29.30133
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - colorama==0.4.6
      - contourpy==1.2.1
      - cycler==0.12.1
      - filelock==3.14.0
      - fonttools==4.52.4
      - fsspec==2024.5.0
      - huggingface-hub==0.23.2
      - idna==3.7
      - intel-openmp==2021.4.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - mkl==2021.4.0
      - mpmath==1.3.0
      - networkx==3.3
      - opencv-python==4.9.0.80
      - packaging==24.0
      - pillow==10.3.0
      - pyparsing==3.1.2
      - pyyaml==6.0.1
      - requests==2.32.2
      - safetensors==0.4.3
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - sympy==1.12
      - tbb==2021.12.0
      - threadpoolctl==3.5.0
      - timm==1.0.3
      - torch==2.3.0
      - torchvision==0.18.0
      - tqdm==4.66.4
      - typing-extensions==4.12.0
      - urllib3==2.2.1
